/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inventale_coregistration_survey_providers_XLearnProvider */

#ifndef _Included_com_inventale_coregistration_survey_providers_XLearnProvider
#define _Included_com_inventale_coregistration_survey_providers_XLearnProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inventale_coregistration_survey_providers_XLearnProvider
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_inventale_coregistration_survey_providers_XLearnProvider_run
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_inventale_coregistration_survey_providers_XLearnProvider
 * Method:    getBestTask
 * Signature: (Ljava/lang/String;[I[I[ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_inventale_coregistration_survey_providers_XLearnProvider_getBestTask
        (JNIEnv *, jobject, jstring, jintArray, jintArray, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
